### ISSUE TITLE
Current To-Do list for website

### ISSUE THREAD

**Issue by ch33sybr3ad** [ch33sybr3ad/RICA-website#9]
## Home Page
- [ ] Responsive Design
  - [ ] Banner is sometimes hidden
  - [ ] About/About Chart is not responsive (eunice) 
  - [ ] Mission statement 
- [x] Mission Statement Section
- [x] Partners Section
## Footer
- [x] Needs a redesign (jason)
## Services
- [ ] sections not responsive
- [ ] reformatting of texts (padding)
- [ ] find proper images to use
## Contact Us
- [x] not responsive
- [x] hours of operation looks funny (jason)
## About Us
- [x] needs structure
- [ ] missing team/management pictures
- [x] still uses old footer
## Misc
- [ ] css clean up (duplicate classes/ids)
- [ ] caching of images, reducing img sizes
- [ ] universal font issue

@euniceschoi
